version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SQLITE_PATH=/app/data/database.sqlite
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - EXPIRESIN=${EXPIRESIN}
      - EXPIRESIN_REFRESH=${EXPIRESIN_REFRESH}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: sh -c "mkdir -p /data && touch /data/database.sqlite" 